### ISSUE TITLE
Tooltips don't seem to work in firefox.

### ISSUE THREAD

**Issue by Zomega** [simmons-tech/directory#4]
Tested on Ubuntu GNOME 13.04 and Windows 7. Results were the same.

The tooltip does not appear anywhere near the element in the SVG, and is not properly formatted. Instead, it shows up near the search bar.
![screenshot from 2013-09-07 22 45 28](https://f.cloud.github.com/assets/879866/1102562/119c8490-1831-11e3-806d-dd7188d35ccc.png)

**Comment by allenpark** [comment]
Seems to work on Ubuntu Firefox
